import type { AnalysisResult } from '@/types/analysis'

export function exportAsJson(analysis: AnalysisResult): void {
  const data = JSON.stringify(analysis, null, 2)
  const blob = new Blob([data], { type: 'application/json' })
  downloadBlob(blob, `optic-shield-report-${analysis.videoId}.json`)
}

export function exportAsPdf(analysis: AnalysisResult): void {
  const html = buildReportHtml(analysis)
  const printWindow = window.open('', '_blank')
  if (!printWindow) return
  printWindow.document.write(html)
  printWindow.document.close()
  printWindow.print()
}

function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

function buildReportHtml(a: AnalysisResult): string {
  const dangerRows = a.dangerZones.map(z =>
    `<tr><td>${formatSec(z.startTime)}</td><td>${formatSec(z.endTime)}</td><td>${z.severity}</td><td>${z.reason}</td></tr>`
  ).join('')

  return `<!DOCTYPE html>
<html><head><title>Optic Shield AI Report</title>
<style>
  body { font-family: system-ui, sans-serif; max-width: 800px; margin: 40px auto; color: #1A1630; }
  h1 { color: #7C5CFC; } h2 { color: #5B8DEF; border-bottom: 1px solid #eee; padding-bottom: 8px; }
  table { width: 100%; border-collapse: collapse; margin: 16px 0; }
  th, td { text-align: left; padding: 8px 12px; border-bottom: 1px solid #eee; font-size: 14px; }
  th { background: #F2F0F7; font-weight: 600; }
  .score { font-size: 48px; font-weight: bold; color: #7C5CFC; }
  .verdict { font-size: 18px; color: #6B6589; }
  .meta { color: #9D97B5; font-size: 13px; }
</style></head><body>
<h1>Optic Shield AI — Safety Report</h1>
<p class="meta">${a.videoMetadata.filename} · ${a.videoMetadata.width}x${a.videoMetadata.height} · ${formatSec(a.videoMetadata.duration)}</p>
<div class="score">${a.safetyScore.toFixed(1)}/100</div>
<div class="verdict">${a.verdict}</div>
${a.aiReport ? `<h2>AI Analysis</h2><p>${a.aiReport}</p>` : ''}
<h2>Danger Zones (${a.dangerZones.length})</h2>
${a.dangerZones.length ? `<table><tr><th>Start</th><th>End</th><th>Severity</th><th>Reason</th></tr>${dangerRows}</table>` : '<p>None detected.</p>'}
<h2>Summary</h2>
<table>
<tr><th>Metric</th><th>Peak/Count</th></tr>
<tr><td>Flash Rate</td><td>${a.flashMetrics.length ? Math.max(...a.flashMetrics.map(m => m.flashCountPerSecond)).toFixed(1) + '/sec' : 'N/A'}</td></tr>
<tr><td>Red Flash</td><td>${a.redFlashMetrics.length ? Math.max(...a.redFlashMetrics.map(m => m.redFlashIntensity)).toFixed(3) : 'N/A'}</td></tr>
<tr><td>Motion</td><td>${a.motionMetrics.length ? Math.max(...a.motionMetrics.map(m => m.motionIntensity)).toFixed(3) : 'N/A'}</td></tr>
<tr><td>Scene Cuts</td><td>${a.sceneCutMetrics.filter(m => m.cutConfidence > 0.8).length} detected</td></tr>
</table>
<p class="meta">Generated by Optic Shield AI · ${new Date().toISOString()}</p>
</body></html>`
}

function formatSec(s: number): string {
  const m = Math.floor(s / 60)
  const sec = Math.floor(s % 60)
  return `${m}:${sec.toString().padStart(2, '0')}`
}
